start npm run publish-to-heroku-test
start npm run publish-to-nrun
start npm run publish-to-hmey
start npm run publish-to-cbdh
start npm run publish-to-cbhr
start npm run publish-to-cbey
start npm run publish-to-atbh
start npm run publish-to-tal-chaim
start npm run publish-to-dinale
start npm run publish-to-dinale-kol-halev
start npm run publish-to-krvtj
start npm run publish-to-merkaz-mazon
start npm run publish-to-bodedim-hertzelia
start npm run publish-to-shorashim
start npm run publish-to-reim
start npm run publish-to-chagsameach
start npm run publish-to-hbhr
start npm run publish-to-tikvabasket
start npm run publish-to-hesed
start npm run publish-to-chasdei
start npm run publish-to-good-people
start npm run publish-to-ladyc
start npm run publish-to-kruvit-sansana
start npm run publish-to-kruvit
start npm run publish-to-plev
start npm run publish-to-yadl
