npm run publish-to-heroku-test
npm run publish-to-nrun
npm run publish-to-hmey
npm run publish-to-cbdh
npm run publish-to-cbhr
npm run publish-to-cbey
npm run publish-to-atbh
npm run publish-to-tal-chaim
npm run publish-to-dinale
npm run publish-to-dinale-kol-halev
npm run publish-to-krvtj
npm run publish-to-merkaz-mazon
npm run publish-to-bodedim-hertzelia
npm run publish-to-shorashim
npm run publish-to-reim
npm run publish-to-chagsameach
npm run publish-to-hbhr
npm run publish-to-tikvabasket
npm run publish-to-hesed
npm run publish-to-chasdei
npm run publish-to-good-people
npm run publish-to-ladyc
npm run publish-to-kruvit-sansana